import logging

from . import core, app
from .app import Komponent, Resource

logger = logging.getLogger(__name__)


class KustApp(app.App):

    def kreate_files(self):
        super().kreate_files()
        self.kust = Kustomization(self)
        self.kust.kreate_file()

    def kreate_from_config(self):
        super().kreate_from_config()
        for shortname in self._shortnames("KustConfigMap"):
            KustConfigMap(self, shortname)
        for res in self.komponents:
            if isinstance(res, Resource):
                self.kreate_patches(res)

    def kreate_patches(self, res) -> None:
        for patch in res.config.get("patches", {}):
            if patch == "HttpProbesPatch":
                HttpProbesPatch(res)
            elif patch == "AntiAffinityPatch":
                AntiAffinityPatch(res)

class Kustomization(Komponent):
    def resources(self):
        # exlcude ConfigMap if it should be generated by kustomize
        return [res for res in self.app.komponents if isinstance(res, Resource) ]

    def config_maps(self):
        return [res for res in self.app.komponents if isinstance(res, KustConfigMap)]


    def patches(self):
        return [res for res in self.app.komponents if isinstance(res, Patch)]

    @property
    def filename(self):
        return "kustomization.yaml"


# Note: this is not a resource
class KustConfigMap(Komponent):
    def _init(self):
        self.vars = {}

    def calc_name(self):
        return f"{self.app.name}-{self.shortname}"

    @property
    def filename(self) -> str:
        #logger.debug(f"not kreating file for {self.name}, will be created by kustomize")
        return None

    def calc_name(self):
        return f"{self.app.name}-{self.shortname}"

    def add_var(self, name, value=None):
        if value is None:
            # TODO: how to get app.values
            value = self.app.values[name]
        self.vars[name] = value

class Patch(Komponent):
    def __init__(self, target: Resource, shortname: str = None, **kwargs):
        self.target = target
        Komponent.__init__(self, target.app, shortname=shortname, **kwargs)

    def _template_vars(self):
        return { **super()._template_vars(),  "target": self.target }

    def _find_config(self):
        root_config = super()._find_config()
        typename = self.kind
        target_config = self.target.config.get("patches",{})
        if typename in target_config and self.shortname in target_config[typename]:
            logger.debug(f"using embedded config {typename}.{self.shortname} from {self.target.kind}.{self.target.shortname}")
            # The embedded_config is first, since the root_config will contain all default values
            embedded_config = target_config[typename][self.shortname]
            return core.DeepChain(embedded_config, root_config)
        return root_config


class HttpProbesPatch(Patch):
    pass
class AntiAffinityPatch(Patch):
    pass
