---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ my.name }}
spec:
  schedule: {{ strukt.schedule }}
  successfulJobsHistoryLimit: {{ my.field.successfulJobsHistoryLimit }}
  concurrencyPolicy: {{ my.field.concurrencyPolicy}}
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ my.name }}
          labels: {}
          annotations:
            app.kubernetes.io/name: {{ my.name }}
            app.kubernetes.io/version: "{{ my.field.image_version }}"
            app.kubernetes.io/component: cronjob
            app.kubernetes.io/part-of: {{ my.field.project }}
            app.kubernetes.io/managed-by: kustomize
            co.elastic.logs/enabled: "true"
            co.elastic.logs/exclude_lines: DEBUG
        spec:
          restartPolicy: OnFailure
          containers:
      containers:
          - name: {{ my.field.container_name }}
            image: {{ my.field.image_repo }}/{{ my.field.image_name }}:{{ my.field.image_version }}
            imagePullPolicy: {{ my.field.imagePullPolicy }}
            resources:
              limits:
                cpu: {{ my.field.cpu_limit }}
                memory: {{ my.field.memory_limit }}
              requests:
                cpu: {{ my.field.cpu_request }}
                memory: {{ my.field.memory_request }}
            envFrom:
              - configMapRef:
              {% for cm in strukt.get("vars",[]) %}
                  name: {{ cm }}
              {% endfor %}
              - secretRef:
              {% for secr in strukt.get("secret-vars",[]) %}
                  name: {{ secr }}
              {% endfor %}
            securityContext:
              runAsNonRoot: true
              runAsUser: {{ my.field.runAsUser }}
              runAsGroup: {{ my.field.runAsGroup }}
            command: "/bin/sh"
            args:
              - '-c'
              - {{ strukt.command }}
      serviceAccountName: {{ strukt.get("serviceAccountName", "")}}
