---
apiVersion: apps/v1
kind: {{ target.kind }}
metadata:
  name: {{ target.name }}
spec:
  template:
    spec:
      containers:
      - name: {{ my.shortname }}
        image: {{ strukt.image }}
        {% if default.imagePullPolicy %}
        imagePullPolicy: {{ my.field.imagePullPolicy }}
        {% endif %}
        securityContext:
          runAsUser: {{ my.field.runAsUser }}
        envFrom:
        - secretRef:
        {% for secr in strukt.get("secret-vars",[]) %}
            name: {{ secr }}
        {% endfor %}
        - configMapRef:
        {% for cm in strukt.get("vars",[]) %}
            name: {{ cm }}
        {% endfor %}
        ports:
        - containerPort: {{ my.field.containerPort }}
          protocol: {{ my.field.protocol }}
        resources:
          limits:
            cpu: {{ my.field.cpu_limit }}
            memory: {{ my.field.memory_limit }}
          requests:
            cpu: {{ my.field.cpu_request }}
            memory: {{ my.field.memory_request }}
